
louvre_ticket_step_1:
    path:    /
    defaults:
        _controller: LouvreTicketPlatformBundle:Ticket:step1

louvre_ticket_step_2:
    path:    /infos
    defaults:
        _controller: LouvreTicketPlatformBundle:Ticket:step2

louvre_ticket_step_3:
    path:    /validation
    defaults:
        _controller: LouvreTicketPlatformBundle:Ticket:step3

louvre_ticket_step_4:
    path:    /payment
    defaults:
        _controller: LouvreTicketPlatformBundle:Ticket:step4

louvre_ticket_cgv:
    path:    /cgv
    defaults:
        _controller: LouvreTicketPlatformBundle:Ticket:cgv

louvre_ticket_tarifs:
    path:    /tarifs
    defaults:
        _controller: LouvreTicketPlatformBundle:Ticket:tarifs

louvre_ticket_mail:
    path:    /mail
    defaults:
        _controller: LouvreTicketPlatformBundle:Ticket:mail



