louvre_ticket_platform_homepage:
    path:     /
    defaults:
        _controller: LouvreTicketPlatformBundle:Default:index

louvre_ticket_step_1:
    path:    /step-1-choice
    defaults:
        _controller: LouvreTicketPlatformBundle:Ticket:step1

louvre_ticket_step_2:
    path:    /step-2-infos
    defaults:
        _controller: LouvreTicketPlatformBundle:Ticket:step2

louvre_ticket_step_3:
    path:    /step-3-validation
    defaults:
        _controller: LouvreTicketPlatformBundle:Ticket:step3

louvre_ticket_step_4:
    path:    /step-4-payment
    defaults:
        _controller: LouvreTicketPlatformBundle:Ticket:step4

louvre_ticket_step_5:
    path:    /step-5-confirmation
    defaults:
        _controller: LouvreTicketPlatformBundle:Ticket:step5

louvre_ticket_step_6:
    path:    /step-6-back_to_louvre_homepage
    defaults:
        _controller: LouvreTicketPlatformBundle:Ticket:step6

louvre_ticket_cgv:
    path:    /cgv
    defaults:
        _controller: LouvreTicketPlatformBundle:Ticket:cgv

louvre_ticket_tarifs:
    path:    /tarifs
    defaults:
        _controller: LouvreTicketPlatformBundle:Ticket:tarifs