services:
    louvre_ticketplatform.formtoentityinjection:
        class: Louvre\TicketPlatformBundle\Services\FormToEntity

    louvre_ticketplatform.price_calculator:
        class: Louvre\TicketPlatformBundle\Services\PriceCalculator

    louvre_ticketplatform.reservation_code:
        class: Louvre\TicketPlatformBundle\Services\ReservationCode

    louvre_ticketplatform.confirmation_mail:
        class: Louvre\TicketPlatformBundle\Services\ConfirmationMail
        arguments:
            - "@mailer"
            - %locale%
