services:
    louvre_ticketplatform.formtoentityinjection:
        class: Louvre\TicketPlatformBundle\Services\FormToEntity

    louvre_ticketplatform.price_calculator:
        class: Louvre\TicketPlatformBundle\Services\PriceCalculator



