services:
    louvre_ticketplatform.formtoentityinjection:
        class: Louvre\TicketPlatformBundle\Services\FormToEntity

    louvre_ticketplatform.price_calculator:
        class: Louvre\TicketPlatformBundle\Services\PriceCalculator
        arguments:
            - "@doctrine.orm.entity_manager"

    louvre_ticketplatform.reservation_code:
        class: Louvre\TicketPlatformBundle\Services\ReservationCode

    louvre_ticketplatform.confirmation_mail:
        class: Louvre\TicketPlatformBundle\Services\ConfirmationMail
        arguments:
            - "@mailer"
            - "@twig"

    louvre_ticketplatform.stripe_payment:
        class: Louvre\TicketPlatformBundle\Services\StripePay
        arguments:
            - %stripe_api_key%