<?php

namespace Louvre\TicketPlatformBundle\Repository;


/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function ticketsCount($visitDate)
    {
        return $this->_em->createQueryBuilder('t')
            ->select('COUNT (0)')
            ->from('LouvreTicketPlatformBundle:Ticket', 't')
            ->where('DATE_DIFF(t.visitDate, :visitDate) = 0')
            ->setParameter('visitDate', $visitDate)
            ->getQuery()
            ->getSingleScalarResult();
        ;
    }
}
