<?php

namespace Louvre\TicketPlatformBundle\Repository;

/**
 * TicketOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketOrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRepoBookingCode($randomCode){
        $repoBookCode = $this->_em
            ->getRepository('LouvreTicketPlatformBundle:TicketOrder')
            ->findOneBy(
                array('bookingCode' => $randomCode)
            )
        ;
        return $repoBookCode;
    }
}
